### ISSUE TITLE
Duplicate Question after like/dislike

### ISSUE THREAD

**Issue by yps1994** [CodeMonkeys3111/AndroidApp#19]
Initially,

![2015-10-30 01 16 48](https://cloud.githubusercontent.com/assets/14330953/10826298/0e821e88-7ea4-11e5-997f-9114d6fa6def.png)

After pressing like button with the question titled with "1", question titled with "2" will overwrite "1".

![2015-10-30 01 16 58](https://cloud.githubusercontent.com/assets/14330953/10826297/0e807768-7ea4-11e5-8044-850a9634c86f.png)

**Comment by yps1994** [comment]
After investigations, this problem roots from pull request #6 , the line changes from

``` java
mFirebaseRef.orderByChild("echo").limitToFirst(200),
```

to

``` java
mFirebaseRef.orderByChild("timestamp").limitToFirst(200),
```

will cause compareTo function in question class (Question.java) error.

``` java
    @Override
    public int compareTo(Question other) {


        if (this.like == other.like) {
            if (other.timestamp == this.timestamp) {
                return 0;
            }
            return other.timestamp > this.timestamp ? -1 : 1;
        }
        return this.like - other.like;
    }

```

An overhaul of the function is needed. This original functions will be overwritten as `@Overwrite` syntax appears and it is for sorting use. The return value is not important, only positive/negative number is used as deciding the order of the question.

**Comment by marvin5064** [comment]
Probably fixed, please check and close the issue
