### ISSUE TITLE
Parent Question content and reply list should scroll tgt

### ISSUE THREAD

**Issue by marvin5064** [CodeMonkeys3111/AndroidApp#20]
![image](https://cloud.githubusercontent.com/assets/14158901/10826582/57b198bc-7ea5-11e5-8192-c68ec2e5ec04.png)
![image](https://cloud.githubusercontent.com/assets/14158901/10826601/6e44ff42-7ea5-11e5-9862-3daaf8f96447.png)

It is better to make they scroll at same time. So that it will provide a better user experience.

**Comment by yps1994** [comment]
Issue will be resolved after my next pull request.

**Comment by magickaichen** [comment]
Ok, remember to close the issue after the problem is solved
