### ISSUE TITLE
Hash Tag Bug

### ISSUE THREAD

**Issue by marvin5064** [CodeMonkeys3111/AndroidApp#66]
![image](https://cloud.githubusercontent.com/assets/14158901/11273855/a26de74a-8f10-11e5-89db-145e6aaee518.png)
HashTag save/display in a wrong way, please save hashtag starting from '#' ending at non-alphabet/numeric char

**Comment by marvin5064** [comment]
Problem happens to both title and content

**Comment by yps1994** [comment]
A fix is working right now.
